# Generated by Django 4.2.6 on 2023-10-29 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_visit_visit_date_time_alter_visit_doctor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="visit",
        ),
        migrations.AddField(
            model_name="visit",
            name="schedule",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visit",
                to="api.schedule",
            ),
        ),
    ]
