# Generated by Django 4.2.6 on 2023-10-29 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_remove_schedule_patient_remove_visit_doctor"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="rating",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="visit",
            name="schedule",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="visits",
                to="api.schedule",
            ),
        ),
    ]
